dubbo:
  application:
    name: storecontract
  protocol:
    name: tri
    port: -1
  registry:
    address: zookeeper://localhost:2181


spring:
  kafka:
    bootstrap-servers: localhost:9092 # Kafka集群地址
    producer: # 生产者配置
      acks: all # 消息确认机制：0-不需要确认，1-只需要leader确认，all-所有副本都需要确认
      retries: 5 # 幂等重试次数
      retry-backoff-ms: 100  # 重试间隔时间
      key-serializer: org.apache.kafka.common.serialization.StringSerializer  # 消息key的序列化器
      value-serializer: org.apache.kafka.common.serialization.StringSerializer  # 消息value的序列化器
      batch-size: 16384 # 批次大小，当批次满了之后才会发送 16k
      buffer-memory: 33554432 # 缓冲区大小 32m
      #      transaction-id-prefix: trxx-id- # 使用事务时配置
      properties:
        linger:
          ms: 100 # 批处理延迟时间上限。不管是否消息大小是否到达 batch-size 或者消息大小到达 buffer-memory 后，都直接发送一次请求。
    consumer: # 消费者配置
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 消息key的反序列化器
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer # 消息value的反序列化器
      auto-offset-reset: earliest # 自动偏移量重置策略：earliest-从头开始消费，latest-从最新的开始消费，none-如果没有偏移量则抛出异常
      enable-auto-commit: false # 是否自动提交偏移量
      auto-commit-interval: 1000  # 自动提交偏移量的间隔时间, 默认5s
      fetch-max-wait: 1000  # poll 一次拉取的阻塞的最大时长，单位：毫秒。这里指的是阻塞拉取需要满足至少 fetch-min-size 大小的消息
      fetch-min-size: 10   # poll 一次消息拉取的最小数据量，单位：字节
      max-poll-records: 100  # poll 一次消息拉取的最大数量
      properties:
        sync-commits: true # 同步提交offset
        isolation:
          level: read_committed # 默认 read_uncommitted 会看到事务未提交的消息
    listener: # 监听器配置
      type: batch # 批量消费
      ack-mode: manual_immediate # 消息确认模式：manual-手动批量确认，auto-自动确认，manual_immediate-立即确认
      concurrency: 1 # 并发消费者数量

      # 重试配置
  #      retry:
  #        # 是否启用重试
  #        enabled: true
  #        # 初始重试间隔时间
  #        initial-interval: 1000
  #        # 最大重试间隔时间
  #        max-interval: 10000
  #        # 重试乘数
  #        multiplier: 2
  #        # 最大重试次数
  #        max-attempts: 3
  datasource:
    type: com.zaxxer.hikari.HikariDataSource      #数据源的类型
    driver-class-name: com.mysql.cj.jdbc.Driver       #数据源的驱动类型
    url: jdbc:mysql://localhost:3306/store_contract?serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false
    username: root                                    #数据源的用户名
    password: 123456                                   #数据源的密码

    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP   # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1


dflong:
  logging:
    enabled: true
    level: INFO
    base-package: com.dflong.storecontract.rest
    log-args: true
    log-result: true
    slow-method-threshold: 500